'use strict';
const $=s=>document.querySelector(s), el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const TOPICS={policy:'Monetary policy',inflation:'Inflation',growth:'Growth',labour:'Labour',markets:'Markets & FX',fiscal:'Fiscal & trade',research:'Research'};
let items=[],limit=20;
const url=s=>{try{const u=new URL(s);return /^https?:$/.test(u.protocol)?u.href:null;}catch{return null;}};
const stamp=s=>Number.isFinite(Date.parse(s))?new Date(s).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'Date unavailable';
function refs(item){const list=[item,...(Array.isArray(item.sources)?item.sources:[])],seen=new Set();return list.filter(s=>{if(!s)return false;const u=url(s.url);if(!u||seen.has(u))return false;seen.add(u);return true;});}
function metadata(item){return [item.source,item.region,stamp(item.ts)].filter(Boolean).join(' · ');}
function sourceNode(s){const row=el('div');row.className='source-row';const a=el('a',s.title||s.source||s.url);a.href=url(s.url);a.target='_blank';a.rel='noopener noreferrer';row.append(a);const p=el('p',[s.source,stamp(s.ts)].filter(Boolean).join(' · '));p.className='meta';row.append(p);return row;}
function storyButton(item,lead=false){const h=el('h2');h.className=lead?'headline':'story-title';const b=el('button',item.title);b.onclick=()=>open(item);h.append(b);return h;}
function summary(item){return typeof item.sum==='string'?item.sum.trim():'';}
function makeChart(item){const c=item.chart;if(!c||!c.title||!c.unit||!c.source||!url(c.source_url)||!Array.isArray(c.points)||c.points.length<2||c.points.length>5000)return null;const pts=c.points.map(p=>({x:Date.parse(p?.date),y:p?.value}));if(pts.some(p=>!Number.isFinite(p.x)||typeof p.y!=='number'||!Number.isFinite(p.y)))return null;pts.sort((a,b)=>a.x-b.x);if(new Set(pts.map(p=>p.x)).size!==pts.length)return null;
 const fig=el('figure');fig.className='chart';fig.append(el('h2',c.title));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('role','img');svg.setAttribute('aria-label',c.title+'; '+c.unit+'; '+pts.length+' observations. Source: '+c.source);fig.append(svg);const cap=el('figcaption','Source: '),a=el('a',c.source);a.href=url(c.source_url);a.target='_blank';a.rel='noopener noreferrer';cap.append(a,document.createTextNode(' · Through '+new Date(pts.at(-1).x).toLocaleDateString()));fig.append(cap);
 const draw=()=>{const w=Math.round(svg.getBoundingClientRect().width);if(!w)return;const h=240,l=62,r=18,t=33,b=48;let lo=Math.min(...pts.map(p=>p.y)),hi=Math.max(...pts.map(p=>p.y));const pad=(hi-lo||Math.abs(hi)*.1||1)*.1;lo-=pad;hi+=pad;const x=v=>l+(v-pts[0].x)/(pts.at(-1).x-pts[0].x)*(w-l-r),y=v=>t+(hi-v)/(hi-lo)*(h-t-b);svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.replaceChildren();const add=(tag,attrs,text)=>{const n=document.createElementNS(svg.namespaceURI,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;svg.append(n);};add('text',{x:l,y:16,fill:'#606771','font-size':11},c.unit);for(let i=0;i<4;i++){const v=lo+i*(hi-lo)/3;add('line',{x1:l,x2:w-r,y1:y(v),y2:y(v),stroke:'#dce0e6'});add('text',{x:l-8,y:y(v)+4,'text-anchor':'end',fill:'#606771','font-size':11},new Intl.NumberFormat(undefined,{maximumFractionDigits:2,notation:'compact'}).format(v));}add('polyline',{points:pts.map(p=>`${x(p.x)},${y(p.y)}`).join(' '),fill:'none',stroke:'#1559c3','stroke-width':2.5});for(const i of [0,pts.length-1])add('text',{x:x(pts[i].x),y:h-24,'text-anchor':i===0?'start':'end',fill:'#606771','font-size':11},new Date(pts[i].x).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'2-digit'}));add('text',{x:(l+w-r)/2,y:h-5,'text-anchor':'middle',fill:'#606771','font-size':11},'Date');};const observer=new ResizeObserver(()=>{if(fig.isConnected)draw();else observer.disconnect();});requestAnimationFrame(()=>{if(fig.isConnected){observer.observe(svg);draw();}});return fig;
}
function feature(item){const chart=makeChart(item);if(chart)return chart;const box=el('aside');box.className='source-feature';const label=el('p','Behind the story');label.className='eyebrow';box.append(label,el('h2','Start with the evidence.'));const sources=refs(item);if(sources.length){for(const s of sources.slice(0,3))box.append(sourceNode(s));}else box.append(el('p','No source link is available for this entry.'));const b=el('button','View source collection ↗');b.className='text-link';b.onclick=()=>open(item);box.append(b);return box;}
function renderTop(){const lead=$('#lead'),more=$('#secondary');lead.replaceChildren();more.replaceChildren();if(!items.length)return;const latest=Math.max(...items.map(i=>Date.parse(i.ts))),day=new Date(latest).toISOString().slice(0,10);const sorted=items.filter(i=>new Date(i.ts).toISOString().slice(0,10)===day).sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0)||Date.parse(b.ts)-Date.parse(a.ts));const chosen=sorted[0],article=el('article'),k=el('p','Lead development / '+(TOPICS[chosen.topic]||chosen.topic||'Economy'));k.className='eyebrow';article.append(k,storyButton(chosen,true));if(summary(chosen)){const p=el('p',summary(chosen));p.className='deck';article.append(p);}const m=el('p',metadata(chosen));m.className='meta';article.append(m);const b=el('button','Explore this development ↗');b.className='text-link';b.onclick=()=>open(chosen);article.append(b);lead.append(article,feature(chosen));const rest=[...sorted.slice(1),...items.filter(i=>!sorted.includes(i))].slice(0,3);for(const item of rest){const a=el('article'),label=el('p',TOPICS[item.topic]||item.topic||'Economy');label.className='eyebrow';a.append(label,storyButton(item));if(summary(item)){const p=el('p',summary(item));p.className='deck';a.append(p);}const m=el('p',metadata(item));m.className='meta';a.append(m);more.append(a);}}
function renderLatest(){const query=$('#query').value.toLowerCase().trim(),region=$('#region').value,topic=$('#topic').value;const list=items.filter(i=>(!region||i.region===region)&&(!topic||i.topic===topic)&&(!query||[i.title,i.source,i.sum,i.topic].join(' ').toLowerCase().includes(query)));$('#result-count').textContent=list.length+' stories';const host=$('#latest');host.replaceChildren();for(const i of list.slice(0,limit)){const row=el('article');row.className='latest-row';const time=el('time',new Date(i.ts).toLocaleDateString(undefined,{month:'short',day:'numeric'}));time.dateTime=i.ts;const text=el('div'),b=el('button',i.title);b.onclick=()=>open(i);const m=el('p',[i.source,TOPICS[i.topic]||i.topic].filter(Boolean).join(' · '));m.className='meta';text.append(b,m);row.append(time,text);host.append(row);}if(!list.length){const p=el('p',items.length?'No stories match. Try another filter.':'No developments are available yet.');p.className='empty';host.append(p);}$('#more').hidden=list.length<=limit;}
function tab(name){for(const n of ['sources','ask']){$('#story-'+n).hidden=n!==name;document.querySelector(`[data-story-tab="${n}"]`).setAttribute('aria-pressed',String(n===name));}}
function open(item){$('#today').hidden=true;$('#reader').hidden=false;$('#reader-title').textContent=item.title;$('#reader-topic').textContent=TOPICS[item.topic]||item.topic||'Economy';$('#reader-meta').textContent=metadata(item);const copy=$('#reader-copy');copy.replaceChildren();if(summary(item))copy.append(el('h2','Feed summary'),el('p',summary(item)));else copy.append(el('p','This feed contains the headline and source reference. Read the original publication, then build your analysis in a research case.'));if(item.why)copy.append(el('h2','Feed interpretation — verify against sources'),el('p',item.why));const original=$('#original');original.hidden=!url(item.url);if(!original.hidden)original.href=url(item.url);const sources=$('#reader-sources');sources.replaceChildren();for(const s of refs(item))sources.append(sourceNode(s));if(!sources.children.length)sources.append(el('p','No linked sources supplied.'));const link='research.html?article='+encodeURIComponent(item.id);$('#research-link').href=link;$('#ask-research-link').href=link;const chart=$('#reader-chart');chart.replaceChildren();const figure=makeChart(item);if(figure)chart.append(figure);tab('sources');history.replaceState(null,'','#story='+encodeURIComponent(item.id));$('#reader-title').focus();window.scrollTo({top:0,behavior:'instant'});}
$('#back').onclick=()=>{$('#reader').hidden=true;$('#today').hidden=false;history.replaceState(null,'',location.pathname+location.search);window.scrollTo({top:0,behavior:'instant'});};document.querySelectorAll('[data-story-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.storyTab));$('#filters').onsubmit=e=>e.preventDefault();$('#filters').oninput=()=>{limit=20;renderLatest();};$('#filters').onreset=()=>setTimeout(()=>{limit=20;renderLatest();},0);$('#more').onclick=()=>{limit+=20;renderLatest();};$('#edition').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'});
(async()=>{try{const r=await fetch('feed.json',{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error();const data=await r.json(),rows=Array.isArray(data)?data:data.items;if(!Array.isArray(rows))throw Error();items=rows.filter(i=>i&&typeof i.title==='string'&&i.title.trim()&&i.id!=null&&Number.isFinite(Date.parse(i.ts))).sort((a,b)=>Date.parse(b.ts)-Date.parse(a.ts));for(const [id,key,labels]of [['region','region',{}],['topic','topic',TOPICS]]){for(const value of [...new Set(items.map(i=>i[key]).filter(Boolean))].sort()){$('#'+id).add(new Option(labels[value]||value,value));}}$('#feed-state').textContent=data.generated&&Number.isFinite(Date.parse(data.generated))?'Feed generated '+stamp(data.generated)+' · Automated selection':'Feed generation time unavailable · Automated selection';renderTop();renderLatest();let id;try{id=decodeURIComponent(location.hash.replace(/^#story=/,''));}catch{id='';}const item=items.find(i=>String(i.id)===id);if(item)open(item);}catch{$('#feed-state').textContent='The news feed could not be loaded. Your research workspace is still available.';renderLatest();}})();
